### ISSUE TITLE
PRÁCTICA CONEXIÓN BASES DE DATOS

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/conexion-bases-de-datos-tadp-isag#1]
[PRACTICA CONEXION DE BASES DE DATOS.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-tadp-isag/files/8725387/PRACTICA.CONEXION.DE.BASES.DE.DATOS.pdf)

**Comment by abicoronel** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
